"""Add UserSession and update Answe

Revision ID: 52b0e0cdd01d
Revises: f2fd318d27b2
Create Date: 2026-03-18 10:44:29.940360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b0e0cdd01d'
down_revision: Union[str, Sequence[str], None] = 'f2fd318d27b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_bot_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rag_bot_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rag_bot_answers', sa.Column('session_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('rag_bot_answers_user_id_fkey'), 'rag_bot_answers', type_='foreignkey')
    op.create_foreign_key(None, 'rag_bot_answers', 'rag_bot_sessions', ['session_id'], ['id'])
    op.drop_column('rag_bot_answers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_bot_answers', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rag_bot_answers', type_='foreignkey')
    op.create_foreign_key(op.f('rag_bot_answers_user_id_fkey'), 'rag_bot_answers', 'rag_bot_users', ['user_id'], ['id'])
    op.drop_column('rag_bot_answers', 'session_id')
    op.drop_table('rag_bot_sessions')
    # ### end Alembic commands ###
